#!/bin/bash
### Wrapper script for launching snakemake workflows ###
clear
echo "Launching snakeworkflow..."

sleep 10
echo "Beginning executing on: $(date)"

if [ ! -d ./slurm ]; then
  mkdir slurm;
fi

conda activate snakemake

snakemake --latency-wait 900 --rerun-incomplete --cluster "sbatch -o ./slurm/%j.log -A perrybe -t 08:00:00 -p inv-iranui-fast,inv-iranui --cpus-per-task {threads} -v" --jobs 6 --local-cores 4 --use-conda --keep-going --use-singularity --restart-times 5 --printshellcmds --reason -R $(snakemake --list-params-changes)

snakemake --report snakemakeReport.html

snakemake --rulegraph | dot -T svg > rulegraph.svg

conda deactivate

echo "snakemake run completed: $(date)"
