#!/bin/bash
### Wrapper script for launching snakemake workflows ###
clear
echo "Launching snakemake workflow..."

sleep 10
echo "Beginning executing on: $(date)"

if [ ! -d ./slurm ]; then
  mkdir slurm;
fi

conda activate snakemake

snakemake --latency-wait 1800 --rerun-incomplete --cluster "sbatch -o ./slurm/%j.log -A perrybe -t 12:00:00 -p inv-iranui --cpus-per-task {threads} -v" --jobs 10 --local-cores 2 --use-conda --keep-going --restart-times 5 --printshellcmds --reason

snakemake --report snakemakeReport.html

snakemake --rulegraph | dot -T svg > rulegraph.svg

conda deactivate

echo "Snakemake run completed: $(date)"
